Entity/Joueur.php
<?php

namespace Al\FFTTBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Joueur
 *
 * @ORM\Table(name="joueur")
 * @ORM\Entity(repositoryClass="Al\FFTTBundle\Repository\JoueurRepository")
 */
class Joueur
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="licence", type="integer", unique=true)
     */
    private $licence;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\OneToMany(targetEntity="Al\FFTTBundle\Entity\Classement", mappedBy="joueur")
     * @ORM\JoinColumn(nullable=false)
     */
    private $classements;

    /**
     * @ORM\OneToMany(targetEntity="Al\FFTTBundle\Entity\Historique", mappedBy="joueur")
     * @ORM\JoinColumn(nullable=false)
     */
    private $historiques;


    /**
     * @ORM\OneToMany(targetEntity="Al\FFTTBundle\Entity\Partie", mappedBy="joueur")
     * @ORM\JoinColumn(nullable=false)
     */
    private $parties;

    public function __construct()
    {
        $this->classements = new ArrayCollection();
        $this->parties = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set licence
     *
     * @param integer $licence
     *
     * @return Joueur
     */
    public function setLicence($licence)
    {
        $this->licence = $licence;

        return $this;
    }

    /**
     * Get licence
     *
     * @return int
     */
    public function getLicence()
    {
        return $this->licence;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Joueur
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return Joueur
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    public function getClassements()
    {
        return $this->classements;
    }

    public function setClassements($classements)
    {
        $this->classements = $classements;
    }

    public function addClassement(Classement $classement){
        $this->classements->add($classement);
        $classement->setJoueur($this);
        return $this;
    }

    public function getLatestClassement() : ?Classement {
        return $this->classements->count() ? $this->classements->last() : null;
    }

    public function getParties()
    {
        return $this->parties;
    }

    public function setParties($parties)
    {
        $this->parties = $parties;
    }


    /**
     * @return Historique[]
     */
    public function getHistoriques()
    {
        return $this->historiques;
    }

    public function setHistoriques($historiques)
    {
        $this->historiques = $historiques;
    }
}

Controller/JoueurController.php
<?php

namespace Al\FFTTBundle\Controller;

use Al\FFTTBundle\Entity\Historique;
use Al\FFTTBundle\Entity\Joueur;
use Al\FFTTBundle\Service\CacheRetriever;
use Al\FFTTBundle\Service\HighchartBuilder;
use Al\FFTTBundle\Service\StatsBuilder;
use FFTTApi\Exception\JoueurNotFound;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Cache\Simple\FilesystemCache;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class JoueurController extends Controller implements ReloadCache
{
    /**
     * @var HighchartBuilder
     */
    private $highchartBuilder;
    /**
     * @var StatsBuilder
     */
    private $statsBuilder;
    /**
     * @var CacheRetriever
     */
    private $cacheRetriever;


    /**
     * JoueurController constructor.
     * @param HighchartBuilder $highchartBuilder
     * @param StatsBuilder $statsBuilder
     * @param CacheRetriever $cacheRetriever
     */
    public function __construct(HighchartBuilder $highchartBuilder, StatsBuilder $statsBuilder, CacheRetriever $cacheRetriever)
    {

        $this->highchartBuilder = $highchartBuilder;
        $this->statsBuilder = $statsBuilder;
        $this->cacheRetriever = $cacheRetriever;
    }

    public function listJoueursAction()
    {
        $joueurs = $this->getDoctrine()->getRepository(Joueur::class)->findAll();
        return $this->render('@AlFFTT/Joueurs/list.html.twig', [
            'joueurs' => $joueurs,
        ]);
    }

    /**
     * @param Joueur $joueur
     * @param HighchartBuilder $highchartBuilder
     * @return \Symfony\Component\HttpFoundation\Response
     * @ParamConverter("joueur")
     */
    public function detailsJoueurAction(Joueur $joueur)
    {

        $this->get('thormeier_breadcrumb.breadcrumb_provider')
            ->getBreadcrumbByRoute('joueur.details')
            ->setRouteParameters([
                'id' => $joueur->getId(),
            ])
            ->setLabelParameters([
                '%name%' => $joueur->getPrenom() . " " . $joueur->getNom(),
            ]);

        return $this->render('@AlFFTT/Joueurs/details.html.twig', [
            'joueur' => $joueur,
            'chart' => $this->statsBuilder->getEvolutionByDay($joueur),
        ]);
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Psr\SimpleCache\InvalidArgumentException
     * @ParamConverter("joueur")
     */
    public function notValidatedMatchJoueurAction(Request $request)
    {
        $joueurLic = $request->get("id");
        $forceReload = $request->get("reload") == "true";

        $parties = $this->cacheRetriever->getNotValidatedMatchs($joueurLic, $forceReload);

        return $this->render("@AlFFTT/Joueurs/notValidatedMatch.html.twig", ["parties" => $parties]);
    }

    public function virtualPointsJoueurAction(Request $request)
    {
        $id = $request->get("id");
        $forceReload = $request->get("reload") == "true";

        $virtualPoints = $this->cacheRetriever->getVirtualPoints($id, $forceReload);

        return new Response(round($virtualPoints, 3));
    }

    /**
     * @param Joueur $joueur
     * @ParamConverter("joueur")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function historiqueJoueurAction(Joueur $joueur)
    {

        $this->get('thormeier_breadcrumb.breadcrumb_provider')
            ->getBreadcrumbByRoute('joueur.details')
            ->setRouteParameters([
                'id' => $joueur->getId(),
            ])
            ->setLabelParameters([
                '%name%' => $joueur->getPrenom() . " " . $joueur->getNom(),
            ]);

        $points = [];
        $xAxis = [];
        /** @var Historique $historique */
        foreach ($joueur->getHistoriques() as $historique) {
            $points[] = $historique->getPoints();
            $xAxis[] = sprintf(
                "%s - %s (%s)",
                $historique->getAnneeDebut(),
                $historique->getAnneeFin(),
                $historique->getPhase()
            );
        }

        $chart = $this->highchartBuilder->buildHisto('container', $xAxis, $points);

        return $this->render('@AlFFTT/Joueurs/historique.html.twig', [
            'joueur' => $joueur,
            'chart' => $chart,
        ]);
    }
}

Resources/views/Joueurs/details.html.twig
{% extends '@AlFFTT/commun/base.html.twig' %}
{% block content %}
    <div class="row">
        <div class="col-sm-12 text-right">
            <i class="glyphicon glyphicon-refresh" onclick="callAjax(true)" style="cursor: pointer;"></i>
        </div>

        <div class="col-sm-4 col-xs-12">
            <h1>
                {{ (joueur.nom ~' '~ joueur.prenom) | upper }}
                {% if app.session.get('player') and app.session.get('player') == joueur.licence %}

                    <a href="#" data-href="{{ path('user.unset') }}" id="user-unset" title="Je ne suis pas ce joueur"
                       style="color: green"><i
                                class="glyphicon glyphicon-user"></i></a>
                {% else %}
                    <a href="#" data-href="{{ path('user.set', {'id': joueur.licence}) }}" id="user-set" title="Je suis ce joueur"><i
                                class="glyphicon glyphicon-user"></i></a>
                {% endif %}
            </h1>
        </div>

        <div class="col-sm-8">
            <div class="row">
                <div class="col-sm-3 col-xs-6 text-center text-uppercase">
                    <span class="points">{{ joueur.latestClassement.pointsOfficiels }}</span>
                    <p>Points licence</p>
                </div>
                <div class="col-sm-3 col-xs-6 text-center text-uppercase">
                    <span class="points">{{ joueur.latestClassement.points | round }}</span>
                    <p>Points en direct</p>
                </div>
                <div class="col-sm-3 col-xs-6 text-center text-uppercase">
                    {% set prog = (joueur.latestClassement.points - joueur.latestClassement.pointsOfficiels) | round %}

                    {% if prog > 0 %}
                        <span class="points positif">{{ prog }}</span>
                    {% else %}
                        <span class="points negatif">{{ prog }}</span>
                    {% endif %}
                    <p>Prog. annuelle</p>
                </div>
                <div class="col-sm-3 col-xs-6 text-center text-uppercase">
                    <span id="virtualPoints" class="points">...</span>
                    <p>Points virtuels</p>
                </div>
                <div class="col-sm-12 text-right">
                    {% if app.session.get('player') and app.session.get('player') != joueur.licence %}
                        {{ getPointsContreAdversaire(joueur.licence) }}
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <a class="btn btn-primary" href="{{ path('adversaire.stats', { 'id' : joueur.licence }) }}">Statistiques</a>
            <a href="{{ path('joueur.historique', { id : joueur.id }) }}" class="btn btn-primary">Historique</a>
        </div>

        <div class="col-sm-12">
            <div id="container"></div>
        </div>
        <div class="col-sm-12">
            {% if joueur.parties is empty %}
                <h2>Aucune partie validée.</h2>
            {% else %}
                <h2>Rencontres validées :</h2>

                <table id="parties" class="tablesorter table table-striped table-hover">
                    <thead>
                    <tr>
                        <th class="header">Date</th>
                        <th class="header">Adversaire</th>
                        <th class="header">Classement</th>
                        <th class="header">Gain</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for partie in joueur.parties %}
                        <tr>
                            <td>
                                {% if partie.isVictoire %}
                                    <span class="victoire positif">V</span>
                                {% else %}
                                    <span class="defaite negatif">D</span>
                                {% endif %}
                                {{ partie.date | date("d/m/Y") }}
                            </td>
                            <td>
                                <a href="{{ path('joueur.adversaire', { id: joueur.id, adversaire : partie.adversaireLicence }) }}">
                                    {{ formatPlayerName(partie.adversaireNom, partie.adversairePrenom) }}
                                </a>
                            </td>
                            <td>{{ partie.adversaireClassement }}</td>
                            <td>
                                {% if partie.pointsObtenus > 0 %}
                                    <span class="positif">{{ partie.pointsObtenus }}</span>
                                {% else %}
                                    <span class="negatif">{{ partie.pointsObtenus }}</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
        <div class="col-sm-12">
            <div id="myDiv">Chargement des parties non validées...</div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<
script
src = "{{ asset("bundles/alfftt/js/highchart.js") }}"></script>
    <script type="text/javascript">
        {{ chart(chart) }}
    </script>
    <script type="application/javascript">

        // call the controller to get the rendered data

        function callAjax(forceReload){

            var route1 = "{{ path('joueur.details.notValidatedMatch', { 'id' : joueur.licence, 'reload' : "PARAM" }) }}";
            var route2 = "{{ path('joueur.details.virtualPoints',  { 'id' : joueur.licence, 'reload' : "PARAM" }) }}";

            $.ajax({
                url: route1.replace("PARAM", forceReload)
            })
                .done(function( data ) {
                    $("#myDiv").html(data);
                    $("#partiesNonValide").tablesorter();
                });

            $.ajax({
                url: route2.replace("PARAM", forceReload)
            })
                .done(function( data ) {
                    $("#virtualPoints").html(data);
                });
        }

        callAjax(false);

        $("#user-set, #user-unset").click(function() {
               $.ajax({
                    url: $(this).data("href")
                })
                .done(function() {
                    window.location.reload(true);
                });

               });
    </script>
{% endblock %}

Resources/views/Joueurs/historique.html.twig
{% extends '@AlFFTT/commun/base.html.twig' %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h1>{{ joueur.prenom ~' '~ joueur.nom }}</h1>
        </div>
        <div class="col-sm-12">
            <div id="container"></div>
        </div>
        <div class="col-sm-12">
            <table id="historique" class="tablesorter table table-striped table-hover">
                <thead>
                <tr>
                    <th class="header">Saison</th>
                    <th class="header">Points</th>
                </tr>
                </thead>
                <tbody>
                {% for historique in joueur.historiques %}
                    <tr>
                        <td>{{ historique.anneeDebut }}-{{ historique.anneeFin }} ({{ historique.phase }})</td>
                        <td>{{ historique.points }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function()
            {
                $("#historique").tablesorter();
            }
        );
    </script>
    <script src="{{ asset("bundles/alfftt/js/highchart.js") }}"></script>
    <script type="text/javascript">
        {{ chart(chart) }}
    </script>
{% endblock %}

Resources/views/Joueurs/list.html.twig
{% extends '@AlFFTT/commun/base.html.twig' %}
{% block content %}
    <h1 class="text-uppercase">Situations mensuelles</h1>
    <table id="table-progression" class="tablesorter table table-striped table-hover">
        <thead>
        <tr>
            <th class="header">Nom / Prénom</th>
            <th class="header">Pts mensuels</th>
            <th class="header">Pts licence</th>
            <th class="header">Prog. mensuelle</th>
            <th class="header">Prog. phase</th>
        </tr>
        </thead>
        <tbody>

        {% for joueur in joueurs %}
            {% if joueur.latestClassement is not null %}
                <tr>
                    <td><a href="{{ path('joueur.details', { id : joueur.id }) }}" >
                            {{ joueur.nom ~' '~ joueur.prenom  }}
                        </a></td>
                    <td>{{ joueur.latestClassement.points | round }}</td>
                    <td>{{ joueur.latestClassement.pointsOfficiels }}</td>
                    <td>
                        {% set progMensuelle =  (joueur.latestClassement.points - joueur.latestClassement.anciensPoints) | round %}
                        {% if progMensuelle > 0 %}
                            <span class="positif">{{ progMensuelle }}</span>
                        {% else %}
                            <span class="negatif">{{ progMensuelle }}</span>
                        {% endif %}
                    </td>
                    <td>
                        {% set progAnuelle =  (joueur.latestClassement.points - joueur.latestClassement.pointsOfficiels) | round %}
                        {% if progAnuelle > 0 %}
                            <span class="positif">{{ progAnuelle }}</span>
                        {% else %}
                            <span class="negatif">{{ progAnuelle }}</span>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block javascript %}
    <script>
        $(function() {
            $("#table-progression").tablesorter({
                sortList: [[2, 1]]
            });
        });
    </script>
{% endblock %}

Resources/views/Joueurs/notValidatedMatch.html.twig
{% block content %}
    {% if parties is not empty %}
        <h2>Rencontres non validées :</h2>

        <table id="partiesNonValide" class="tablesorter table table-striped table-hover">
            <thead>
            <tr>
                <th class="header">Date</th>
                <th class="header">Adversaire</th>
                <th class="header">Classement</th>
                <th class="header">Points virtuels</th>
            </tr>
            </thead>
            <tbody>
            {% for dataPartie in parties %}
                <tr>
                    <td>
                        {% if dataPartie.partie.isVictoire %}
                            <span class="victoire positif">V</span>
                        {% else %}
                            <span class="defaite negatif">D</span>
                        {% endif %}
                        {{ dataPartie.partie.date | date("d/m/Y") }}
                    </td>
                    <td>
                        <a href="{{ path('adversaire.search.choose', { "nom" : dataPartie.partie.adversaireNom, "prenom" : dataPartie.partie.adversairePrenom}) }}">
                            {{ formatPlayerName(dataPartie.partie.adversaireNom, dataPartie.partie.adversairePrenom) }}
                        </a>
                    </td>
                    <td>{{ dataPartie.partie.adversaireClassement }}</td>
                    <td>
                        {% if dataPartie.virtualPoint > 0 %}
                            <span class="positif">{{ dataPartie.virtualPoint }}</span>
                        {% else %}
                            <span class="negatif">{{ dataPartie.virtualPoint }}</span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

{% endblock %}